["${XDG_DATA_HOME}/zsh/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/fzf-tab-source"]
    type = "git-repo"
    url = "https://github.com/Freed-Wu/fzf-tab-source.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git/"
    refreshPeriod = "336h"
