["${XDG_DATA_HOME}/zsh/fzf-tab/fzf-tab.plugin.zsh"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/fzf-tab-source/fzf-tab-source.plugin.zsh"]
    type = "git-repo"
    url = "https://github.com/Freed-Wu/fzf-tab-source.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git/"
    refreshPeriod = "336h"

["${XDG_DATA_HOME}/zsh/zsh-history-substring-search/zsh-history-substring-search.zsh"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git/"
    refreshPeriod = "336h"
